name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test application
        run: python -m py_compile app.py
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-first-devops-app:latest .
      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-first-devops-app:latest 